// public/svelte-vite/src/App.svelte
<script>
  import { onMount } from 'svelte';

  let message = '';

  onMount(async () => {
    const res = await fetch('/api/hello');
    const data = await res.json();
    message = data.message;
  });

  const loadApi = async () => {
    const res = await fetch('/api/hello');
    const data = await res.json();
    message = data.message;
  };
</script>

<h1>Svelte + Vite SPA</h1>

<div class="api-status">
  {#if message}
    <p>{message}</p>
  {:else}
    <p>Click to load API data</p>
  {/if}
</div>

<button on:click={loadApi}>Load from /api/hello</button>

// public/react-vite/src/App.jsx
import { useEffect, useState } from 'react';

function App() {
  const [message, setMessage] = useState('');

  useEffect(() => {
    fetch('/api/hello')
      .then(res => res.json())
      .then(data => {
        setMessage(data.message);
      });
  }, []);

  const loadApi = () => {
    fetch('/api/hello')
      .then(res => res.json())
      .then(data => setMessage(data.message));
  };

  return (
    <div className="container">
      <h1>React + Vite SPA</h1>
      <div className="api-status">
        {message ? <p>{message}</p> : <p>Click to load API data</p>}
      </div>
      <button onClick={loadApi}>Load from /api/hello</button>
    </div>
  );
}

export default App;
